name: Build

on: [ pull_request ]

jobs:
    format:
        name: Run Build on codebase
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@main
            -   uses: actions/setup-node@v1
                with:
                    node-version: '12.20.2'
            -   name: Install Dependencies
                run: |
                    npm install
            -   name: Run Build Prod
                run: |
                    npm run build:prod
