name: Codestyle

on: [ pull_request ]

jobs:
    format:
        name: Run Prettier on codebase
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@main
            -   uses: actions/setup-node@v1
                with:
                    node-version: '12.20.2'
            -   name: Install Dependencies
                run: |
                    npm install
            -   name: Run Prettier
                run: |
                    node node_modules/prettier/index.js --write 'src/**/*.{js,ts,css}'

    format-check:
        name: Run Lint on codebase
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@main
            -   uses: actions/setup-node@v1
                with:
                    node-version: '12.20.2'
            -   name: Install Dependencies
                run: |
                    npm install
            -   name: Run Lint
                run: |
                    node node_modules/tslint/bin/tslint --write 'src/**/*.{js,ts,css}'
